### ISSUE TITLE
jarfile Client.jar Not Found

### ISSUE THREAD

**Issue by shijcnju** [DeMaCS-UNICAL/Angry-HEX#1]
I can not find the jarfile Client.jar when I run './dev.angryhex.sh run client'.
I'm not sure if I misunderstand the ReadMe.

**Comment by shijcnju** [comment]
I see, I should make file at first.

**Comment by peschue** [comment]
Hello shijcnju, were you able to create the jar file?

**Comment by shijcnju** [comment]
@peschue 
not yet :-( 
Can you give some hints?

**Comment by peschue** [comment]
Did you already try to run the following?

`./dev.angryhex.sh install all`

The version that is currently committed might require you to do this with sudo.

See also the Readme file for commands for individual installation parts: https://github.com/DeMaCS-UNICAL/Angry-HEX/blob/master/README.md

**Comment by shijcnju** [comment]
@peschue Thanks for your advice! But it still not works when I run `./dev.angryhex.sh`. Should I install GNU? As the error is 
`autoreconf: command not found. Please install GNU autoconf.`
This error is from the command `./bootstrap.sh`

**Comment by shijcnju** [comment]
I've read your paper 《An Artificial Player for Angry Birds Based on Declarative Knowledge Bases》. Great work 👍

**Comment by peschue** [comment]
It is not GNU, it is `GNU autoconf` or simply `autoconf`.

Did you get errors during the installation process? Normally the script should install all required Ubuntu packages. Are you using Ubuntu Linux?

**Comment by shijcnju** [comment]
@peschue I'm using MAC

**Comment by peschue** [comment]
We were able to run the agent on MacOS but unfortunately this requires quite some tweaking and installation of various packages.

At that point we would recommend you to setup Ubuntu (16.04) in a virtual machine and try to install the agent there.

**Comment by shijcnju** [comment]
@peschue I see. Thank you~

**Comment by peschue** [comment]
As we have nobody maintaining Angry-HEX on MacOS at the moment, I will close this issue for the moment as "wontfix".
